apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc-new   # NEW NAME
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: kops-csi-1-21
---
apiVersion: v1
kind: Pod
metadata:
  name: mysql-cleaner
spec:
  containers:
  - name: cleaner
    image: busybox
    command: [ "sh", "-c", "rm -rf /mnt/mysql/*; sleep 3600" ]
    volumeMounts:
    - name: mysql-data
      mountPath: /mnt/mysql
  volumes:
  - name: mysql-data
    persistentVolumeClaim:
      claimName: mysql-pvc-new
  restartPolicy: Never
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: rootpassword
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-data
        persistentVolumeClaim:
          claimName: mysql-pvc-new
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  type: ClusterIP
  selector:
    app: mysql
  ports:
  - port: 3306
    targetPort: 3306
